### 安装最新版tensorflow

### 查看tensorflow版本号

In [1]:
import tensorflow as tf
import numpy as np
print("TensorFlow verson:",tf.__version__)

TensorFlow verson: 2.5.0-rc3


In [2]:
print("Eager execution is:",tf.executing_eagerly())

Eager execution is: True


## 创建张量

### 张量的.numpy()方法

In [3]:
tf.constant([[1,2],[3,4]])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [4]:
a=tf.constant([[1,2],[3,4]])
a.numpy()

array([[1, 2],
       [3, 4]])

In [5]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [6]:
print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


### 参数为数字 

In [7]:
tf.constant(1.0)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [8]:
tf.constant(1.)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [9]:
tf.constant(1.0,dtype=tf.float64)

<tf.Tensor: shape=(), dtype=float64, numpy=1.0>

### 参数为NumPy数组

In [10]:
import numpy as np

In [11]:
tf.constant(np.array([1,2]))

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [12]:
tf.constant(np.array([1.0,2.0]))

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([1., 2.])>

In [13]:
tf.constant(np.array([1.0,2.0]),dtype=tf.float32)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

### 改变数据类型

In [14]:
a=tf.constant(np.array([1,2]))
b=tf.cast(a,dtype=tf.float32)
b.dtype

tf.float32

In [15]:
a=tf.constant(123456789,dtype=tf.int32)
tf.cast(a,tf.int16)

<tf.Tensor: shape=(), dtype=int16, numpy=-13035>

In [16]:
tf.constant(True)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [17]:
a=tf.constant([True,False])
tf.cast(a,tf.int32)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 0])>

In [18]:
a=tf.constant([-1,0,1,2])
tf.cast(a,tf.bool)

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True, False,  True,  True])>

### 参数为字符串

In [19]:
tf.constant("hello")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello'>

### tf.convert_to_tensor()函数

In [20]:
na=np.arange(12).reshape(3,4)
ta=tf.convert_to_tensor(na)

In [21]:
type(na)

numpy.ndarray

In [22]:
type(ta)

tensorflow.python.framework.ops.EagerTensor

### is_tensor()函数

In [23]:
tf.is_tensor(ta)

True

In [24]:
tf.is_tensor(na)

False

### isinstance()函数

In [25]:
isinstance(ta,tf.Tensor)

True

In [26]:
isinstance(na,np.ndarray)

True

### 创建全0张量和全1张量

In [27]:
tf.ones(shape=(2,1))

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>

In [28]:
tf.ones([6])

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1.], dtype=float32)>

In [29]:
tf.ones([2,3],tf.int32)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]])>

### 创建元素之都相同的张量

tf.fill( dims, value )
fill()函数没有dtype参数，根据value参数自动判断数据类

In [30]:
tf.fill([2,3],9)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9]])>

In [31]:
tf.fill([2,3],9.0)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[9., 9., 9.],
       [9., 9., 9.]], dtype=float32)>

In [32]:
tf.constant(9,shape=[2,3])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9]])>

In [33]:
tf.fill(dims=[2,3],value=9)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9]])>

In [34]:
tf.constant(value=9,shape=[2,3])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9]])>

### 创建随机数张量——正态分布

In [35]:
tf.random.normal([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.22331865, -0.3542728 ],
       [ 0.80913   , -0.45724005]], dtype=float32)>

In [36]:
tf.random.normal([3,3,3],mean=0.0,stddev=2.0)

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[-2.1830432 ,  0.44035733,  2.2306368 ],
        [ 0.91174185, -2.6969721 ,  0.8440948 ],
        [-1.7800547 , -0.7813911 ,  2.8567414 ]],

       [[-0.6180981 , -2.9935277 , -2.4493046 ],
        [ 3.2967162 ,  3.283345  ,  0.4214928 ],
        [-1.1976746 ,  2.0155494 , -3.2665079 ]],

       [[ 1.6705142 , -1.2300117 , -2.2832327 ],
        [ 1.4307058 ,  2.1201544 ,  1.7290045 ],
        [ 2.562097  , -1.5794144 , -0.45793834]]], dtype=float32)>

In [37]:
tf.random.truncated_normal([3,3,3],mean=0.0,stddev=2.0)

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[-1.5680887 , -1.522795  , -0.02963714],
        [ 0.9576182 ,  1.4606217 , -0.38567647],
        [-0.52940416, -2.2038312 , -1.6500967 ]],

       [[ 2.842066  ,  0.83692276,  1.2031388 ],
        [-2.2976875 , -1.4100516 ,  2.386148  ],
        [-1.9514604 , -0.5934799 ,  0.9254127 ]],

       [[-0.0677485 ,  1.0746552 ,  0.99043375],
        [-0.22348183, -0.2051413 , -2.298032  ],
        [ 1.3262212 ,  0.27267146,  0.55521995]]], dtype=float32)>

### 创建随机种子

In [39]:
tf.random.set_seed(8)
tf.random.normal([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.2074401, -0.7452462],
       [ 0.6908678, -0.7635988]], dtype=float32)>

### 创建均匀分布张量

In [41]:
tf.random.uniform(shape=(3,3),minval=0,maxval=10,dtype='int32')

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[6, 8, 3],
       [9, 5, 1],
       [8, 6, 1]])>

### 随机打乱函数

In [43]:
x=tf.constant([[1,2],[3,4],[5,6]])
tf.random.shuffle(x)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 6],
       [3, 4]])>

In [45]:
y=[1,2,3,4,5,6]
tf.random.shuffle(y)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 5, 4, 2, 3, 6])>

In [46]:
z=np.arange(5)
tf.random.shuffle(z)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([3, 1, 2, 4, 0])>

### 创建序列——tf.range()函数

In [47]:
tf.range(10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [48]:
tf.range(10,delta=2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8])>

In [50]:
tf.range(1,10,delta=2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

### 获取Tensor对象的形状、元素总数和维度

In [58]:
tf.constant([[1,2],[3,4]])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [59]:
a=tf.constant([[1,2],[3,4]])
print('ndim:',a.ndim)
print('dtype:',a.dtype)
print('shape:',a.shape)

ndim: 2
dtype: <dtype: 'int32'>
shape: (2, 2)


In [60]:
tf.shape(a)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2])>

In [61]:
tf.size(a)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [62]:
tf.rank(a)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

# 小结