# 解析法多元线性回归

### 加载样本数据

In [1]:
import numpy as np

In [4]:
x1=np.array([137.97,104.50,100.00,124.32,79.20,99.00,124.00,114.00,106.69,138.05,53.75,46.91,68.00,63.02,81.26,86.21])
x2=np.array([3,2,2,3,1,2,3,2,2,3,1,1,1,1,2,2])
y=np.array([145.00,110.00,93.00,116.00,65.32,104.00,118.00,91.00,62.00,133.00,51.00,45.00,78.50,69.65,75.69,95.30])


In [5]:
x1.shape,x2.shape,y.shape

((16,), (16,), (16,))

### 数据处理

In [6]:
x0=np.ones(len(x1))

In [7]:
X=np.stack((x0,x1,x2),axis=1)
X

array([[  1.  , 137.97,   3.  ],
       [  1.  , 104.5 ,   2.  ],
       [  1.  , 100.  ,   2.  ],
       [  1.  , 124.32,   3.  ],
       [  1.  ,  79.2 ,   1.  ],
       [  1.  ,  99.  ,   2.  ],
       [  1.  , 124.  ,   3.  ],
       [  1.  , 114.  ,   2.  ],
       [  1.  , 106.69,   2.  ],
       [  1.  , 138.05,   3.  ],
       [  1.  ,  53.75,   1.  ],
       [  1.  ,  46.91,   1.  ],
       [  1.  ,  68.  ,   1.  ],
       [  1.  ,  63.02,   1.  ],
       [  1.  ,  81.26,   2.  ],
       [  1.  ,  86.21,   2.  ]])

In [8]:
Y=np.array(y).reshape(-1,1)
Y

array([[145.  ],
       [110.  ],
       [ 93.  ],
       [116.  ],
       [ 65.32],
       [104.  ],
       [118.  ],
       [ 91.  ],
       [ 62.  ],
       [133.  ],
       [ 51.  ],
       [ 45.  ],
       [ 78.5 ],
       [ 69.65],
       [ 75.69],
       [ 95.3 ]])

### 求解模型参数

In [9]:
Xt=np.transpose(X) #计算X矩阵转置
XtX_1=np.linalg.inv(np.matmul(Xt,X))#计算矩阵的逆
XtX_1Xt=np.matmul(XtX_1,Xt)#矩阵相乘
W=np.matmul(XtX_1Xt,Y)#矩阵相乘

In [10]:
W

array([[11.96729093],
       [ 0.53488599],
       [14.33150378]])

In [12]:
W=W.reshape(-1)
W

array([11.96729093,  0.53488599, 14.33150378])

In [13]:
print("多元线性回归方程")
print("Y=",W[1],"*x1+",W[2],"*x2+",W[0])

多元线性回归方程
Y= 0.5348859949724712 *x1+ 14.331503777673714 *x2+ 11.96729093053445


### 预测房价

In [16]:
print("请输入房屋面积和房间数，预测房屋销售价格")
x1_test=float(input("商品房面积："))
x2_test=int(input("房间数："))

y_pred=W[1]*x1_test+W[2]*x2_test+W[0]
print("预测价格：",round(y_pred,2),"万元")

请输入房屋面积和房间数，预测房屋销售价格
商品房面积：200.00
房间数：5
预测价格： 190.6 万元
